<template>
    <div>
        <!-- Faded Black Background that is clickable to cancel -->
        <div v-if="focus" @click="focus = false" class="bg-black opacity-25 absolute right-0 left-0 top-0 bottom-0 z-10"></div>

        <div class="relative z-10">
            <!-- Magnifying Glass SVG -->            
            <div class="absolute">
                <svg viewBox="0 0 24 24" class="w-5 h-5 mt-2 ml-2">
                    <path fill-rule="evenodd" d="M20.2 18.1l-1.4 1.3-5.5-5.2 1.4-1.3 5.5 5.2zM7.5 12c-2.7 0-4.9-2.1-4.9-4.6s2.2-4.6 4.9-4.6 4.9 2.1 4.9 4.6S10.2 12 7.5 12zM7.5.8C3.7.8.7 3.7.7 7.3s3.1 6.5 6.8 6.5c3.8 0 6.8-2.9 6.8-6.5S11.3.8 7.5.8z" clip-rule="evenodd"/>
                </svg>
            </div>
            <!-- Input Field For Search -->                        
            <input class="w-64 bg-gray-200 border border-gray-400 mr-6 pl-8 pr-3 py-1 rounded-full text-sm
            focus:outline-none focus:border-blue-500 focus:shadow focus:bg-gray-100" type="text"
            placeholder="Search" id="searchTerm" v-model="searchTerm" @input="searchloading = true" @focus="focus = true; results=[]; searchloading = true; search()" @blur="searchloading ==false;">
            <!-- Box for displaying search results and loading icon -->            
            <div v-if="focus && searchTerm.length > 0" class="absolute bg-blue-900 text-white rounded-lg p-4 w-96 right-0 mr-6 mt-2 shadow z-20">
            <!-- Message if searchTerm is below 3 characters -->            
            <div v-if="searchTerm.length < 3 && results == 0"> Please input at least 3 characters </div>
                <!-- SVG for Loading -->                             
                <div v-if="searchloading == true && searchTerm.length >= 3">                    
                    <p class="flex justify-center"> Loading... </p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(42, 67, 101); display: block; shape-rendering: auto;" width="91px" height="91px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                        <circle cx="50" cy="50" r="23" stroke-width="8" stroke="#a0b4ef" stroke-dasharray="36.12831551628262 36.12831551628262" fill="none" stroke-linecap="round">
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1.0416666666666665s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
                        </circle>
                        <!-- [ldio] generated by https://loading.io/ -->
                    </svg>    
                </div>                
                <!-- "No contacts found" message -->
                <div v-if="results == 0 && searchloading == false"> No results found for '{{ searchTerm }}' </div>                
                <!-- loop for showing search results on a list. On clicking on a router link, "focus" variable (i.e parent
                div of the result box) is toggled and causes it closes -->
                <div v-for="result in results" v-bind:key="result.id" @click="focus = false">
                    <!-- Router link needs to be a block element to have padding and margin -->
                    <router-link :to="result.links.self" class="block py-2">
                        <div class="flex items-center">
                            <UserCircle :name="result.data.name" />

                            <div class="pl-3">
                                <p> {{ result.data.name }} </p>
                                <p> {{ result.data.company }} </p>

                            </div>
                        </div>    
                    </router-link>
                </div>

            </div>
        </div>            
    </div>
</template>

<script>
    import _ from 'lodash';
    import UserCircle from '../components/UserCircle';
    export default {
        name: "SearchBar",
        mounted() {
            
        },
        props:[
            
        ],

        data: function(){ 
            return{
                searchTerm: '',
                results: [],
                focus: false,                
                searchloading: false,
            }
        },

        components: {
            UserCircle,
        },

        computed: {
            
        },

        methods: {     
            // this is using lodash(needs to be imported above). It delays the api call by 1 second before calling so if someone types
            // too fast in the search bar, it will delay 300 millisecond (0.3 sec) before firing the api call. Or else, the continuous
            // requests will consume too much of the application's resources(e.g website will be slowed down)
            search: _.debounce(function(e){
                if(this.searchTerm.length < 3){
                    return '';
                }
                    axios.post('api/search', {searchTerm: this.searchTerm})
                    .then(response => {
                        this.results = response.data.data;
                        console.log(this.results);
                        this.searchloading = false;
                    }).catch(error => {

                    });                                           
            }, 300 ),          

        },

        watch: {
            searchTerm: function(val){
                this.results = [];
                this.search();
                if(this.searchTerm.length < 3){
                    this.results = [];
                }
                console.log(val);
            }
        }
    }

</script>

<style>

</style>